# http://travis-ci.org/#!/agschwender/pilbox
language: python
python:
  - 2.6
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  - 3.3
env:
  - PYTHONPATH=$PYTHONPATH:$PWD
before_install:
  - sudo apt-get update
  - sudo apt-get install libjpeg8-dev libfreetype6-dev zlib1g-dev
  - sudo apt-get install libwebp-dev liblcms2-dev
  - sudo apt-get install python-numpy python-opencv python-pycurl
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install tornado==4.0.2 Pillow==2.8.1 coveralls
  - pip install pep8==1.6.2 pyflakes==0.8.1
before_script:
  - pep8 --exclude=test pilbox
  - pyflakes pilbox/*.py
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then coverage run -m pilbox.test.runtests; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then coveralls; fi
