# http://travis-ci.org/#!/agschwender/pilbox
language: python
python:
  - 2.7
  - 3.2
env:
  - PYTHONPATH=$PYTHONPATH:$PWD
virtualenv:
    system_site_packages: true
before_install:
  - sudo apt-get install libjpeg8-dev libfreetype6-dev zlib1g-dev
  - sudo apt-get install libwebp-dev liblcms1-dev
  - sudo apt-get install python-numpy python-opencv
install:
    - pip install --use-mirrors tornado==3.1 Pillow==2.1.0 coveralls==3.6
script:
    - coverage run -m pilbox.test.runtests
after_success:
    - coveralls
